### ISSUE TITLE
Security Object hash verification fails if only 1 container specified to be protected (test ID 10.4.1.1)

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#303]
If the Security Object specifies that only 1 container be protected, test ID 10.4.1.1 ("The actual hash of the data elements on the PIV card are identical to their corresponding hash values present in the security object.") fails.  The problem is reproducible.  The Printed Information Container, CHUID container, and Security Object are available upon request.

Pertinent info from the debug log file:

2021-02-23 12:03:20,614 DEBUG [Thread-4] g.g.c.t.SP800_73_4SecurityObjectTests [SP800_73_4SecurityObjectTests.java:179] [Security object: 0x1 about to read PRINTED_INFORMATION_OID from card
2021-02-23 12:03:20,618 ERROR [Thread-4] g.g.p.c.c.SecurityObject [SecurityObject.java:325] wrong size in DataGroupHashValues : not in (2..16)
2021-02-23 12:03:20,618 ERROR [Thread-4] g.g.p.c.c.SecurityObject [SecurityObject.java:371] LDSSecurityObject was null
2021-02-23 12:03:20,618 ERROR [Thread-4] g.g.c.testProgress [GuiTestListener.java:123] Test atom 10.4.1.1:1 => oid = 2.16.840.1.101.3.7.2.144.0 failed
2021-02-23 12:03:20,619 ERROR [Thread-4] g.g.p.GuiTestListener [GuiTestListener.java:131] Caused by:
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
            at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:36)
            at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:42)
            at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:37)
            at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:115)
            at gov.gsa.conformancelib.tests.SP800_73_4SecurityObjectTests.sp800_73_4_Test_37(SP800_73_4SecurityObjectTests.java:261)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
            at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
            at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
            at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
            at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
            at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
            at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
            at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$0(HierarchicalTestExecutor.java:114)
            at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:133)
            at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:101)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
            at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
            at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
            at java.util.stream.ReferencePipeline.forEach(Unknown Source)
            at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
            at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
            at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
            at java.util.stream.ReferencePipeline.forEach(Unknown Source)
            at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:101)
            at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:38)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
            at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
            at java.util.Iterator.forEachRemaining(Unknown Source)
            at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
            at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
            at java.util.stream.ReferencePipeline.forEach(Unknown Source)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
            at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
            at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
            at java.util.Iterator.forEachRemaining(Unknown Source)
            at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
            at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
            at java.util.stream.ReferencePipeline.forEach(Unknown Source)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
            at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
            at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
            at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
            at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
            at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
            at gov.gsa.pivconformancegui.TestExecutionController.runAllTests(TestExecutionController.java:250)
            at gov.gsa.pivconformancegui.SimpleTestExecutionPanel$2.lambda$actionPerformed$0(SimpleTestExecutionPanel.java:197)
            at java.lang.Thread.run(Unknown Source)

**Comment by bob-fontana** [comment]
The requirement for the security object is to have 2..16 elements per the cited specification https://www.icao.int/publications/Documents/9303_p10_cons_en.pdf.

The BC libraries reject the security object on that card due to only data group when the spec requires 2..16.  

 LDSSecurityObject ::= SEQUENCE {
  version LDSSecurityObjectVersion,
  hashAlgorithm DigestAlgorithmIdentifier,
  dataGroupHashValues SEQUENCE SIZE (2..ub-DataGroups) OF
  DataGroupHash
}

**Comment by maxwellfunk** [comment]
Need to research coordination between NIST and ICAO

**Comment by maxwellfunk** [comment]
NIST SP 800-73-4 (sec 3.1.7) and NIST SP 800-78-4 (sec 3.2.3) both reference ICAO MRTD for security object specification.  MRTD Part 10 section 5.2.1 indicates how many are required in the sequence.
